name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: ocr_labeler

    - name: Checkout pd-book-tools dependency
      uses: actions/checkout@v4
      with:
        repository: ConcaveTrillion/pd-book-tools
        path: pd-book-tools

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies and setup
      run: make install
      working-directory: ocr_labeler

    - name: Run CI pipeline
      run: make ci
      working-directory: ocr_labeler

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: distribution-packages
        path: ocr_labeler/dist/
        retention-days: 30
